name: Code Style

on:
    pull_request:
    push:
        branches:
            - master

jobs:
    code-style:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@master

            - name: Select PHP version
              uses: shivammathur/setup-php@master
              with:
                  php-version: '7.4'

            - name: Install Composer dependencies
              run: composer install

            - name: Run tests for coverage
              run: ./vendor/bin/phpcs
